"""Initial Migration

Revision ID: 001
Revises: 
Create Date: 2021-05-01 09:51:32.506520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=False),
    sa.Column('receiver', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('template_params', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_receiver'), 'emails', ['receiver'], unique=False)
    op.create_index(op.f('ix_emails_request_id'), 'emails', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_request_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_receiver'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
