[tool.black]
verbose = true
target-version = ["py39"]
exclude = "migrations"

[tool.isort]
atomic = true
color_output = true
verbose = true
only_modified = true
ensure_newline_before_comments = true
force_single_line = true
include_trailing_comma = true
use_parentheses = true
skip = "migrations"
force_grid_wrap = 0
lines_after_imports = 2
lines_between_types = 1
line_length = 88
multi_line_output = 3
py_version = 39

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = "tests"
addopts = "--cov-append --cov-branch --strict-config --verbose --code-highlight yes --color yes --cov app --cov-report term"
