name: "deploy"

on:
  push:
    branches: ["release"]

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "Deploy the web dyno"
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: email-service-web
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
